# Generated by Django 5.0.14 on 2026-02-04 19:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Grading Scale",
                "verbose_name_plural": "Grading Scales",
                "db_table": "grading_scales",
            },
        ),
        migrations.CreateModel(
            name="CumulativeAggregate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cumulative_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("cumulative_units", models.PositiveIntegerField(default=0)),
                (
                    "cumulative_average",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cumulative_credits_attempted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "cumulative_credits_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "cumulative_grade_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cgpa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("cumulative_grade", models.CharField(blank=True, max_length=50)),
                ("total_units_passed", models.PositiveIntegerField(default=0)),
                ("total_units_failed", models.PositiveIntegerField(default=0)),
                (
                    "last_semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.semester",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cumulative_aggregate",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cumulative Aggregate",
                "verbose_name_plural": "Cumulative Aggregates",
                "db_table": "cumulative_aggregates",
            },
        ),
        migrations.CreateModel(
            name="MarksUploadBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("total_records", models.PositiveIntegerField(default=0)),
                ("successful_records", models.PositiveIntegerField(default=0)),
                ("failed_records", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_batches",
                        to="academics.semester",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_batches",
                        to="academics.unit",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marks Upload Batch",
                "verbose_name_plural": "Marks Upload Batches",
                "db_table": "marks_upload_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grade", models.CharField(max_length=10)),
                ("min_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade_points", models.DecimalField(decimal_places=2, max_digits=3)),
                ("classification", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=100)),
                (
                    "grading_scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_definitions",
                        to="grades.gradingscale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Definition",
                "verbose_name_plural": "Grade Definitions",
                "db_table": "grade_definitions",
                "ordering": ["grading_scale", "-min_marks"],
                "unique_together": {("grading_scale", "grade")},
            },
        ),
        migrations.CreateModel(
            name="SemesterAggregate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("units_taken", models.PositiveIntegerField(default=0)),
                (
                    "term_average",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "credits_attempted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "credits_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_grade_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("gpa", models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ("units_passed", models.PositiveIntegerField(default=0)),
                ("units_failed", models.PositiveIntegerField(default=0)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aggregates",
                        to="academics.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_aggregates",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semester Aggregate",
                "verbose_name_plural": "Semester Aggregates",
                "db_table": "semester_aggregates",
                "ordering": ["student", "-semester__year"],
                "unique_together": {("student", "semester")},
            },
        ),
        migrations.CreateModel(
            name="StudentResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=10)),
                (
                    "grade_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "credit_attempted",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "credit_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("supplementary", "Supplementary"),
                            ("incomplete", "Incomplete"),
                            ("exempted", "Exempted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pass",
                        max_length=20,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("is_repeat", models.BooleanField(default=False)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="academics.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="students.student",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="academics.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Result",
                "verbose_name_plural": "Student Results",
                "db_table": "student_results",
                "ordering": ["student", "semester", "unit"],
                "unique_together": {("student", "unit", "semester", "attempt_number")},
            },
        ),
    ]
