# Generated by Django 5.0.14 on 2026-05-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentresult',
            options={'ordering': ['unit_registration__semester_registration__student_enrollment__student__reg_no', 'unit_registration__unit__code'], 'verbose_name': 'Student Result', 'verbose_name_plural': 'Student Results'},
        ),
    ]
