# Generated by Django 5.0.14 on 2026-05-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_studentresult_options'),
        ('students', '0003_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='unit_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.semesterregistrationunit'),
        ),
    ]
