# Generated by Django 5.0.14 on 2026-06-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0003_alter_studentresult_unit_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="semesteraggregate",
            name="semester_grade",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
