# Generated by Django 5.0.14 on 2026-03-09 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "db_table": "academic_years",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("head_of_department", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
                "ordering": ["school", "name"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("dean", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "db_table": "schools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "programme_type",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("bachelors", "Bachelor's Degree"),
                            ("masters", "Master's Degree"),
                            ("phd", "Doctor of Philosophy"),
                        ],
                        default="bachelors",
                        max_length=20,
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        choices=[
                            ("semester", "Semester Based"),
                            ("module", "Module Based"),
                        ],
                        default="semester",
                        max_length=20,
                    ),
                ),
                ("duration_years", models.PositiveIntegerField(default=4)),
                ("total_credits_required", models.PositiveIntegerField(default=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programmes",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
                "db_table": "programmes",
                "ordering": ["department", "name"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("module_number", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="academics.programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "db_table": "modules",
                "ordering": ["programme", "module_number"],
                "unique_together": {("programme", "module_number")},
            },
        ),
        migrations.AddField(
            model_name="department",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="academics.school",
            ),
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "semester_type",
                    models.CharField(
                        choices=[
                            ("first", "First Semester"),
                            ("second", "Second Semester"),
                            ("third", "Third Semester"),
                            ("supplementary", "Supplementary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("registration_deadline", models.DateField(blank=True, null=True)),
                ("marks_submission_deadline", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="semesters",
                        to="academics.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
                "db_table": "semesters",
                "ordering": ["-year", "-start_date"],
                "unique_together": {("academic_year", "semester_type")},
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "credit_hours",
                    models.DecimalField(decimal_places=2, default=3.0, max_digits=4),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("elective", "Elective"),
                            ("common", "Common Course"),
                        ],
                        default="core",
                        max_length=20,
                    ),
                ),
                ("recommended_year", models.PositiveIntegerField(default=1)),
                ("recommended_semester", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True, related_name="required_for", to="academics.unit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "db_table": "units",
                "ordering": ["code"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("name", "school")},
        ),
        migrations.CreateModel(
            name="SemesterUnit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lecturer", models.CharField(blank=True, max_length=200)),
                ("max_students", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_units",
                        to="academics.programme",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_units",
                        to="academics.semester",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_offerings",
                        to="academics.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semester Unit",
                "verbose_name_plural": "Semester Units",
                "db_table": "semester_units",
                "ordering": ["semester", "unit__code"],
                "unique_together": {("semester", "unit", "programme")},
            },
        ),
        migrations.CreateModel(
            name="ProgrammeUnit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year_of_study", models.PositiveIntegerField(blank=True, null=True)),
                ("semester_number", models.PositiveIntegerField(blank=True, null=True)),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_units",
                        to="academics.module",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programme_units",
                        to="academics.programme",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programme_units",
                        to="academics.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme Unit",
                "verbose_name_plural": "Programme Units",
                "db_table": "programme_units",
                "ordering": [
                    "programme",
                    "year_of_study",
                    "semester_number",
                    "unit__code",
                ],
                "unique_together": {("programme", "unit")},
            },
        ),
    ]
