# Generated by Django 5.0.14 on 2026-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmeunit',
            options={'ordering': ['programme', 'recommended_program_year', 'recommended_semester', 'unit__code'], 'verbose_name': 'Programme Unit', 'verbose_name_plural': 'Programme Units'},
        ),
        migrations.RenameField(
            model_name='programmeunit',
            old_name='year_of_study',
            new_name='recommended_program_year',
        ),
        migrations.RenameField(
            model_name='programmeunit',
            old_name='semester_number',
            new_name='recommended_semester',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
