# Generated by Django 5.0.14 on 2026-03-09 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcript",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transcript_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "verification_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "transcript_type",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("unofficial", "Unofficial"),
                            ("provisional", "Provisional"),
                        ],
                        default="official",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("issued", "Issued"),
                            ("revoked", "Revoked"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="transcripts/"),
                ),
                ("data_snapshot", models.JSONField(default=dict)),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="transcripts/qr/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "from_semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transcripts_from",
                        to="academics.semester",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_transcripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_transcripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transcripts",
                        to="students.student",
                    ),
                ),
                (
                    "to_semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transcripts_to",
                        to="academics.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcript",
                "verbose_name_plural": "Transcripts",
                "db_table": "transcripts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transcript_type",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("unofficial", "Unofficial"),
                            ("provisional", "Provisional"),
                        ],
                        default="official",
                        max_length=20,
                    ),
                ),
                ("purpose", models.TextField(blank=True)),
                ("copies_requested", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_requests",
                        to="students.student",
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="transcripts.transcript",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcript Request",
                "verbose_name_plural": "Transcript Requests",
                "db_table": "transcript_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptVerification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("verification_method", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="transcripts.transcript",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcript Verification",
                "verbose_name_plural": "Transcript Verifications",
                "db_table": "transcript_verifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
