# Generated by Django 5.0.14 on 2026-03-09 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reg_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Registration Number"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("national_id", models.CharField(blank=True, max_length=50)),
                ("admission_year", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("graduated", "Graduated"),
                            ("suspended", "Suspended"),
                            ("withdrawn", "Withdrawn"),
                            ("deferred", "Deferred"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("graduation_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="students/photos/"
                    ),
                ),
                (
                    "admission_semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admitted_students",
                        to="academics.semester",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="academics.programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "students",
                "ordering": ["reg_no"],
            },
        ),
        migrations.CreateModel(
            name="SemesterRegistration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year_of_study", models.PositiveIntegerField()),
                ("is_repeat", models.BooleanField(default=False)),
                ("registration_date", models.DateField(auto_now_add=True)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="academics.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_registrations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semester Registration",
                "verbose_name_plural": "Semester Registrations",
                "db_table": "semester_registrations",
                "ordering": ["-semester__academic_year__year", "-semester__start_date"],
                "unique_together": {("student", "semester")},
            },
        ),
        migrations.CreateModel(
            name="ModuleRegistration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_repeat", models.BooleanField(default=False)),
                ("registration_date", models.DateField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="academics.module",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_registrations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Registration",
                "verbose_name_plural": "Module Registrations",
                "db_table": "module_registrations",
                "ordering": ["module__module_number"],
                "unique_together": {("student", "module")},
            },
        ),
        migrations.CreateModel(
            name="UnitRegistration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("dropped", "Dropped"),
                            ("completed", "Completed"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                (
                    "module_registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_registrations",
                        to="students.moduleregistration",
                    ),
                ),
                (
                    "semester_registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_registrations",
                        to="students.semesterregistration",
                    ),
                ),
                (
                    "semester_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="academics.semesterunit",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_registrations",
                        to="students.student",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="academics.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit Registration",
                "verbose_name_plural": "Unit Registrations",
                "db_table": "unit_registrations",
                "ordering": ["student", "unit__code"],
            },
        ),
        migrations.AddConstraint(
            model_name="unitregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("semester_registration__isnull", False)),
                fields=("semester_registration", "semester_unit"),
                name="unique_semester_unit_reg",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("module_registration__isnull", False)),
                fields=("module_registration", "unit"),
                name="unique_module_unit_reg",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitregistration",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("module_registration__isnull", True),
                        ("semester_registration__isnull", False),
                    ),
                    models.Q(
                        ("module_registration__isnull", False),
                        ("semester_registration__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="registration_type_exclusive",
            ),
        ),
    ]
