# Generated by Django 5.0.14 on 2026-05-26 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_programmeunit_options_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semesterregistration',
            old_name='year_of_study',
            new_name='program_year',
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semester_registrations', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('pending', 'Pending'), ('approved', 'Approved'), ('deferred', 'Deferred')], default='registered', max_length=20),
        ),
        migrations.CreateModel(
            name='SemesterRegistrationUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_status', models.CharField(choices=[('registered', 'Registered'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('deferred', 'Deferred'), ('repeat', 'Repeat'), ('retake', 'Retake'), ('supplementary', 'Supplementary'), ('credit_transfer', 'Credit Transfer')], default='registered', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('module_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_registrations', to='students.moduleregistration')),
                ('semester_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_registrations', to='students.semesterregistration')),
                ('semester_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='academics.semesterunit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='academics.unit')),
            ],
            options={
                'verbose_name': 'Semester Registration Unit',
                'verbose_name_plural': 'Semester Registration Units',
                'db_table': 'semester_registration_units',
                'ordering': ['semester_registration', 'unit__code'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_date', models.DateField()),
                ('cohort', models.CharField(max_length=50)),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn'), ('deferred', 'Deferred')], default='active', max_length=20)),
                ('expected_graduation_date', models.DateField(blank=True, null=True)),
                ('admission_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='academics.semester')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.programme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'db_table': 'student_enrollments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='semesterregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='student_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_registrations', to='students.studentenrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='semesterregistration',
            unique_together={('student_enrollment', 'semester')},
        ),
    ]
