# Generated by hand

from django.db import migrations

def migrate_academic_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    StudentEnrollment = apps.get_model('students', 'StudentEnrollment')
    SemesterRegistration = apps.get_model('students', 'SemesterRegistration')
    SemesterRegistrationUnit = apps.get_model('students', 'SemesterRegistrationUnit')
    UnitRegistration = apps.get_model('students', 'UnitRegistration')
    
    # 1. Create StudentEnrollment records for every Student
    for student in Student.objects.all():
        # Get raw programme field if it exists
        programme_id = getattr(student, 'programme_id', None)
        if programme_id:
            admission_year = getattr(student, 'admission_year', 2025)
            status = getattr(student, 'status', 'active')
            admission_semester_id = getattr(student, 'admission_semester_id', None)
            graduation_date = getattr(student, 'graduation_date', None)
            
            StudentEnrollment.objects.get_or_create(
                student=student,
                programme_id=programme_id,
                defaults={
                    'admission_date': student.created_at.date() if student.created_at else None,
                    'cohort': f"{admission_year}" if admission_year else "2025",
                    'current_status': status or 'active',
                    'admission_semester_id': admission_semester_id,
                    'expected_graduation_date': graduation_date,
                }
            )

    # 2. Update SemesterRegistration to set student_enrollment and academic_year
    for reg in SemesterRegistration.objects.all():
        student_id = getattr(reg, 'student_id', None)
        if student_id:
            student = Student.objects.get(id=student_id)
            programme_id = getattr(student, 'programme_id', None)
            # Find matching enrollment
            enrollment = StudentEnrollment.objects.filter(student=student, programme_id=programme_id).first() or StudentEnrollment.objects.filter(student=student).first()
            if enrollment:
                reg.student_enrollment = enrollment
                reg.academic_year = reg.semester.academic_year
                reg.save()

    # 3. Migrate UnitRegistration to SemesterRegistrationUnit
    for ur in UnitRegistration.objects.all():
        sem_reg = ur.semester_registration
        if sem_reg:
            SemesterRegistrationUnit.objects.get_or_create(
                id=ur.id,  # Keep the exact same ID so StudentResult FK remains valid!
                defaults={
                    'semester_registration': sem_reg,
                    'unit': ur.unit,
                    'unit_status': ur.status or 'registered',
                    'attempt_number': 1,
                    'semester_unit': ur.semester_unit,
                    'module_registration': ur.module_registration,
                }
            )

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_unitregistration_module_registration_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_academic_data, reverse_code=reverse_migration),
    ]
