# Generated by hand

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_studentresult_unit_registration'),
        ('students', '0003_data_migration'),
    ]

    operations = [
        # 1. Remove old fields from Student model
        migrations.RemoveField(
            model_name='student',
            name='admission_semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='graduation_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        
        # 2. Delete the old UnitRegistration model
        migrations.DeleteModel(
            name='UnitRegistration',
        ),
        
        # 3. Add constraint on SemesterRegistrationUnit
        migrations.AddConstraint(
            model_name='semesterregistrationunit',
            constraint=models.UniqueConstraint(fields=('semester_registration', 'unit'), name='unique_semester_reg_unit'),
        ),
        
        # 4. Alter unique together on StudentEnrollment
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'programme')},
        ),
        
        # 5. Remove fields from SemesterRegistration
        migrations.RemoveField(
            model_name='semesterregistration',
            name='is_repeat',
        ),
        migrations.RemoveField(
            model_name='semesterregistration',
            name='student',
        ),
        
        # 6. Alter student_enrollment and academic_year on SemesterRegistration to be non-nullable
        migrations.AlterField(
            model_name='semesterregistration',
            name='student_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_registrations', to='students.studentenrollment'),
        ),
        migrations.AlterField(
            model_name='semesterregistration',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semester_registrations', to='academics.academicyear'),
        ),
    ]
