# Generated by Django 5.0.14 on 2026-06-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_alter_programmeunit_options_and_more"),
        ("students", "0004_cleanup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semesterregistration",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="semester_registrations",
                to="academics.academicyear",
            ),
        ),
        migrations.AlterField(
            model_name="semesterregistration",
            name="student_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semester_registrations",
                to="students.studentenrollment",
            ),
        ),
    ]
